# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



source 'https://github.com/CocoaPods/Specs.git'


target 'TargetName' do
use_frameworks!

pod 'TinderSwipeView’ , '~> 1.1.8'
end
